services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
    App\Tests\Stub\:
        resource: '../tests/Stub/*'

    App\Common\Clock: '@App\Tests\Stub\FakeClock'

security:
    firewalls:
        dev:
            pattern:  ^/
            security: false