services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'


security:
    firewalls:
        dev:
            pattern:  ^/
            security: false